// Development demo mode (no ANTHROPIC_API_KEY, NODE_ENV != production).
// Answers are scripted, not generated by Claude, but they run through the
// same permission-checked tools against the real workspace records, so links,
// sources and confirmation previews behave exactly as they do live. Every
// message is stored and shown with a "Demo response" label.
import { runTool, type LumeCtx } from './tools.ts';
import { addDays, formatISO, weekday } from '../../shared/dates.ts';
import { STAGE_TEMPLATES, STAGES, type Stage } from '../../shared/templates.ts';

interface Sink {
  status: (label: string) => void;
  delta: (text: string) => void;
  flush: () => void;
  signal: AbortSignal;
}

type T = { ref: string; title: string; due: string | null; due_label: string; assignee_ids: string[]; priority: string; status: string; project: string | null; id: string };
type E = { ref: string; title: string; when: string; starts_at: string | null; all_day: boolean; attendees: string[] };

async function tool<R>(ctx: LumeCtx, sink: Sink, label: string, name: string, input: unknown): Promise<R> {
  sink.status(label);
  const r = await runTool(ctx, name, input);
  sink.flush();
  if (r.isError) throw new DemoClarify(r.content);
  return JSON.parse(r.content) as R;
}

class DemoClarify extends Error {}

const DAYS = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];

function parseDay(text: string, today: string): string | null {
  const t = text.toLowerCase();
  if (/\btoday\b/.test(t)) return today;
  if (/\btomorrow\b/.test(t)) return addDays(today, 1);
  const iso = t.match(/\b(\d{4}-\d{2}-\d{2})\b/);
  if (iso) return iso[1];
  for (let i = 0; i < 7; i++) {
    if (new RegExp(`\\b${DAYS[i]}\\b`).test(t)) {
      const delta = (i - weekday(today) + 7) % 7 || 7;
      return addDays(today, delta);
    }
  }
  return null;
}

function parseTime(text: string): string | null {
  const m = text.toLowerCase().match(/\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)\b|\b([01]?\d|2[0-3]):([0-5]\d)\b/);
  if (!m) return null;
  if (m[3]) {
    let h = Number(m[1]) % 12;
    if (m[3] === 'pm') h += 12;
    return `${String(h).padStart(2, '0')}:${m[2] ?? '00'}`;
  }
  return `${String(Number(m[4])).padStart(2, '0')}:${m[5]}`;
}

const addMinutes = (hhmm: string, mins: number) => {
  const [h, m] = hhmm.split(':').map(Number);
  const total = Math.min(h * 60 + m + mins, 23 * 60 + 59);
  return `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`;
};

function quoted(text: string): string | null {
  const m = text.match(/[“"']([^“”"']{2,120})[”"']/);
  return m ? m[1].trim() : null;
}

const list = (items: string[]) => items.map((i) => `- ${i}`).join('\n');

async function streamOut(text: string, sink: Sink) {
  const parts = text.match(/\S+\s*|\s+/g) ?? [];
  for (let i = 0; i < parts.length; i += 3) {
    if (sink.signal.aborted) break;
    sink.delta(parts.slice(i, i + 3).join(''));
    await new Promise((r) => setTimeout(r, 14));
  }
}

export async function demoRespond(ctx: LumeCtx, message: string, sink: Sink): Promise<string> {
  let text: string;
  try {
    text = await compose(ctx, message, sink);
  } catch (err) {
    if (err instanceof DemoClarify) text = `I couldn’t prepare that yet: ${err.message} Could you give me a little more detail?`;
    else throw err;
  }
  await streamOut(text, sink);
  return text;
}

async function compose(ctx: LumeCtx, message: string, sink: Sink): Promise<string> {
  const m = message.toLowerCase();
  const today = ctx.today;

  if (/\b(claude|anthropic|model|who are you|what are you)\b/.test(m))
    return 'I’m Lume, Lumera Creative’s AI assistant. In production I’m powered by Anthropic’s Claude models. This workspace is running in development demo mode, so my answers here are scripted responses built from your real records rather than generated by Claude.';

  // ── Changes (proposals) ──
  if (/\b(mark|set)\b.*\b(done|complete|completed|finished)\b|\bcomplete\b.*\btask\b/.test(m)) {
    const mine = await tool<{ tasks: T[] }>(ctx, sink, 'Checking tasks', 'list_tasks', { view: 'mine', limit: 50 });
    const name = quoted(message);
    const match = mine.tasks.find((t) => (name ? t.title.toLowerCase().includes(name.toLowerCase()) : m.includes(t.title.toLowerCase())));
    if (!match) return `Which task should I mark complete? Your open tasks include:\n${list(mine.tasks.slice(0, 5).map((t) => t.ref))}`;
    await tool(ctx, sink, 'Preparing the change', 'propose_update_task', { task_id: match.id, status: 'done' });
    return `I’ve prepared marking ${match.ref} as complete. Confirm below to save it.`;
  }

  if (/\b(reschedule|move|push)\b/.test(m) && /\btask|due|to\b/.test(m)) {
    const day = parseDay(m.split(/\bto\b/).pop() ?? m, today);
    const mine = await tool<{ tasks: T[] }>(ctx, sink, 'Checking tasks', 'list_tasks', { view: 'team', limit: 50 });
    const name = quoted(message);
    const match = mine.tasks.find((t) => (name ? t.title.toLowerCase().includes(name.toLowerCase()) : m.includes(t.title.toLowerCase())));
    if (!match) return 'Which task would you like to reschedule? Put its title in quotes, for example: reschedule “Homepage copy” to Friday.';
    if (!day) return `When should ${match.ref} be due instead?`;
    await tool(ctx, sink, 'Preparing the change', 'propose_update_task', { task_id: match.id, due_date: day });
    return `I’ve prepared moving ${match.ref} to ${formatISO(day, { weekday: 'short', month: 'short', day: 'numeric' })}. Confirm below to save it.`;
  }

  if (/\b(schedule|book|set up|add)\b.*\b(meeting|call|event|review|check-in|sync)\b/.test(m)) {
    const day = parseDay(m, today);
    const start = parseTime(m);
    const title = quoted(message) ?? (m.includes('call') ? 'Client call' : m.includes('review') ? 'Review' : 'Team meeting');
    if (!day) return `What day should “${title}” be on?`;
    if (!start) return `What time should “${title}” start on ${formatISO(day, { weekday: 'short', month: 'short', day: 'numeric' })}, and how long should it be?`;
    const duration = /\b(\d+)\s*(min|minutes)\b/.exec(m)?.[1];
    const end = addMinutes(start, duration ? Number(duration) : /\bhour\b/.test(m) ? 60 : 30);
    const r = await tool<{ warnings: string[] }>(ctx, sink, 'Preparing an event', 'propose_create_event', { title, date: day, start_time: start, end_time: end });
    return `I’ve prepared “${title}” for ${formatISO(day, { weekday: 'short', month: 'short', day: 'numeric' })}. Review the details below and confirm to add it to the calendar.${r.warnings.length ? `\n\nHeads up: ${r.warnings.join(' ')}` : ''}`;
  }

  const stage = STAGES.find((s) => m.includes(s.value) || m.includes(s.label.toLowerCase()))?.value as Stage | undefined;
  if (/\b(task list|checklist|plan out|tasks for|draft)\b/.test(m) && stage) {
    const projects = await tool<{ projects: { id: string; name: string; ref: string }[] }>(ctx, sink, 'Looking at projects', 'list_projects', { status: 'open' });
    const project = projects.projects.find((p) => m.includes(p.name.toLowerCase()));
    const tasks = STAGE_TEMPLATES[stage].map((t) => ({ title: t.title, priority: t.priority, checklist: t.checklist }));
    await tool(ctx, sink, 'Drafting a task list', 'propose_task_list', { project_id: project?.id, tasks });
    return `Here’s a practical ${STAGES.find((s) => s.value === stage)!.label.toLowerCase()} task list${project ? ` for ${project.ref}` : ''}. Nothing is saved until you confirm, and you can edit the list first.`;
  }

  if (/\b(create|add|new|make)\b.*\btask\b|\bremind me to\b/.test(m)) {
    const title = quoted(message) ?? message.replace(/.*\b(task|remind me to)\b(\s+to)?/i, '').replace(/\b(today|tomorrow|on \w+day|by \w+day)\b.*$/i, '').trim();
    if (!title || title.length < 3) return 'What should the task be called?';
    const due = parseDay(m, today);
    const r = await tool<{ warnings: string[] }>(ctx, sink, 'Preparing a task', 'propose_create_task', { title: title.slice(0, 120), due_date: due ?? undefined, assignee_ids: [ctx.userId] });
    return `I’ve prepared the task below${due ? ` due ${formatISO(due, { weekday: 'short', month: 'short', day: 'numeric' })}` : ''}, assigned to you. Confirm to save it or edit the details first.${r.warnings.length ? `\n\nHeads up: ${r.warnings.join(' ')}` : ''}`;
  }

  // ── Questions ──
  if (/\bprofit|goal|target|money|\$/.test(m)) {
    const p = await tool<Record<string, unknown>>(ctx, sink, 'Checking the profit goal', 'get_profit_summary', {});
    if (p.permitted === false) return 'You don’t have access to profit figures in this workspace. An owner or admin can change that in workspace settings.';
    const lines = [`For ${p.month}, the team has recorded **${p.recorded}** of profit against a **${p.target}** target — ${p.percent_of_target}% of the goal.`];
    if (p.achieved) lines.push(`The goal is met${p.over_target_by ? `, ${p.over_target_by} over target` : ''}.`);
    else lines.push(`${p.remaining_to_target} remains${p.days_left_in_month !== undefined ? ` with ${p.days_left_in_month} days left in the month` : ''}.`);
    lines.push('These are recorded profit entries, not revenue.');
    if (!p.achieved) {
      const projects = await tool<{ projects: { ref: string; status: string; stage: string }[] }>(ctx, sink, 'Looking at projects', 'list_projects', { status: 'open' });
      const closing = projects.projects.filter((x) => ['review', 'launch'].includes(x.stage)).slice(0, 2);
      if (closing.length) lines.push(`Suggestion: Projects near the finish line — ${closing.map((x) => x.ref).join(' and ')} — are the likeliest places for the next profit entry. Confirm invoicing is scheduled.`);
      else lines.push('Suggestion: Review which active projects have billable milestones this month and record profit as it lands.');
    }
    return lines.join('\n\n');
  }

  if (/\boverdue|late|behind\b/.test(m)) {
    const r = await tool<{ tasks: T[] }>(ctx, sink, 'Checking tasks', 'list_tasks', { view: 'overdue', limit: 20 });
    if (r.tasks.length === 0) return 'Nothing is overdue right now.';
    return `There ${r.tasks.length === 1 ? 'is 1 overdue task' : `are ${r.tasks.length} overdue tasks`}:\n${list(r.tasks.map((t) => `${t.ref} — ${t.due_label}`))}\n\nSuggestion: Reschedule anything that has slipped for a known reason, so the calendar stays honest.`;
  }

  if (/\btomorrow\b/.test(m) && /\b(schedul|meeting|calendar|on|have)\b/.test(m)) {
    const d = addDays(today, 1);
    const r = await tool<{ events: E[] }>(ctx, sink, 'Checking the calendar', 'list_events', { from: d, to: d, scope: 'team' });
    const t = await tool<{ tasks: T[] }>(ctx, sink, 'Checking tasks', 'list_tasks', { view: 'team', due_from: d, due_to: d });
    const parts: string[] = [];
    parts.push(r.events.length ? `The team has ${r.events.length} event${r.events.length === 1 ? '' : 's'} tomorrow:\n${list(r.events.map((e) => `${e.ref} — ${e.when.split(', ').slice(1).join(', ') || 'all day'}`))}` : 'There’s nothing on the team calendar tomorrow.');
    if (t.tasks.length) parts.push(`Due tomorrow:\n${list(t.tasks.map((x) => x.ref))}`);
    return parts.join('\n\n');
  }

  if (/\b(this week|deadline|due this week|next week)\b/.test(m)) {
    const r = await tool<{ tasks: T[] }>(ctx, sink, 'Checking tasks', 'list_tasks', { view: 'team', due_from: today, due_to: addDays(today, 6) });
    const p = await tool<{ projects: { ref: string; due: string | null }[] }>(ctx, sink, 'Looking at projects', 'list_projects', { status: 'open' });
    const projectDeadlines = p.projects.filter((x) => x.due && !x.due.includes('overdue')).slice(0, 5);
    const parts = [r.tasks.length ? `Task deadlines in the next 7 days:\n${list(r.tasks.map((t) => `${t.ref} — ${t.due_label}`))}` : 'No task deadlines in the next 7 days.'];
    if (projectDeadlines.length) parts.push(`Project due dates:\n${list(projectDeadlines.map((x) => `${x.ref} — ${x.due}`))}`);
    return parts.join('\n\n');
  }

  // Default: focus / plan my day.
  const [events, mine, overdue] = [
    await tool<{ events: E[] }>(ctx, sink, 'Checking the calendar', 'list_events', { from: today, to: today, scope: 'mine' }),
    await tool<{ tasks: T[] }>(ctx, sink, 'Checking tasks', 'list_tasks', { view: 'mine', due_to: addDays(today, 2) }),
    await tool<{ tasks: T[] }>(ctx, sink, 'Checking tasks', 'list_tasks', { view: 'overdue', assignee_id: ctx.userId }),
  ];
  const parts: string[] = [];
  parts.push(events.events.length ? `You have ${events.events.length} meeting${events.events.length === 1 ? '' : 's'} today:\n${list(events.events.map((e) => `${e.ref} — ${e.all_day ? 'all day' : e.when.split(', ').slice(1).join(', ')}`))}` : 'Your calendar is clear today.');
  const dueSoon = mine.tasks.filter((t) => t.due && t.due >= today);
  if (overdue.tasks.length) parts.push(`Overdue and assigned to you:\n${list(overdue.tasks.slice(0, 5).map((t) => `${t.ref} — ${t.due_label}`))}`);
  if (dueSoon.length) parts.push(`Due in the next two days:\n${list(dueSoon.slice(0, 5).map((t) => `${t.ref} — ${t.due_label}`))}`);
  const top = [...overdue.tasks, ...dueSoon].sort((a, b) => (a.priority === 'high' ? -1 : 0) - (b.priority === 'high' ? -1 : 0))[0];
  const upcoming = events.events.filter((e) => e.starts_at && new Date(e.starts_at).getTime() > Date.now());
  if (top) parts.push(`Suggestion: Start with ${top.ref}${upcoming.length ? ' before your next meeting' : ''}, then work down the list by due date.`);
  else if (!events.events.length) parts.push('Suggestion: It’s a quiet day — a good time to plan the week or clear small tasks in your queue.');
  return parts.join('\n\n');
}
