// Extracts the Solar icons the app uses into a small offline collection, so
// the UI never fetches icons from a third-party API at runtime.
import { readFileSync, writeFileSync } from 'node:fs';
import { getIcons } from '@iconify/utils';

const solar = JSON.parse(readFileSync(new URL('../node_modules/@iconify-json/solar/icons.json', import.meta.url), 'utf8'));
const names = [
  'add-circle-linear',
  'add-square-linear',
  'alt-arrow-down-linear',
  'alt-arrow-left-linear',
  'alt-arrow-right-linear',
  'arrow-left-linear',
  'arrow-right-linear',
  'arrow-up-linear',
  'bell-bold',
  'notes-bold',
  'notes-linear',
  'bell-linear',
  'calendar-add-linear',
  'calendar-bold',
  'calendar-linear',
  'calendar-mark-linear',
  'camera-linear',
  'case-round-bold',
  'case-round-linear',
  'chart-2-linear',
  'chat-round-dots-linear',
  'chat-square-linear',
  'check-circle-bold',
  'check-circle-linear',
  'checklist-bold',
  'checklist-linear',
  'checklist-minimalistic-linear',
  'clipboard-list-linear',
  'clock-circle-linear',
  'close-circle-linear',
  'close-square-linear',
  'copy-linear',
  'crown-minimalistic-linear',
  'danger-circle-linear',
  'danger-triangle-linear',
  'database-linear',
  'document-text-linear',
  'dollar-minimalistic-linear',
  'download-minimalistic-linear',
  'eye-closed-linear',
  'eye-linear',
  'filter-linear',
  'flag-linear',
  'folder-with-files-bold',
  'folder-with-files-linear',
  'global-linear',
  'hamburger-menu-linear',
  'history-linear',
  'home-2-bold',
  'home-2-linear',
  'inbox-linear',
  'info-circle-linear',
  'key-linear',
  'letter-linear',
  'letter-opened-linear',
  'link-linear',
  'list-linear',
  'lock-keyhole-minimalistic-linear',
  'lock-keyhole-minimalistic-unlocked-linear',
  'logout-2-linear',
  'magnifer-linear',
  'map-point-linear',
  'menu-dots-bold',
  'minus-circle-linear',
  'monitor-linear',
  'monitor-smartphone-linear',
  'moon-linear',
  'palette-linear',
  'pen-linear',
  'pin-linear',
  'refresh-linear',
  'repeat-linear',
  'settings-bold',
  'settings-linear',
  'shield-check-linear',
  'smartphone-linear',
  'sort-by-time-linear',
  'square-arrow-right-up-linear',
  'stop-circle-linear',
  'sun-2-linear',
  'target-linear',
  'trash-bin-minimalistic-linear',
  'undo-left-linear',
  'user-check-rounded-linear',
  'user-plus-rounded-linear',
  'user-rounded-linear',
  'users-group-rounded-linear',
  'users-group-two-rounded-linear',
  'wallet-money-bold',
  'wallet-money-linear',
  'widget-4-linear',
  'widget-add-linear',
  'widget-linear',
];
const subset = getIcons(solar, names);
const missing = names.filter((n) => !subset?.icons[n] && !subset?.aliases?.[n]);
if (missing.length) {
  console.error('Missing Solar icons:', missing.join(', '));
  process.exit(1);
}
writeFileSync(new URL('../src/lib/solar-subset.json', import.meta.url), JSON.stringify(subset));
console.log(`Wrote ${names.length} Solar icons.`);
